codecov:
  token: 8644e1fa-9dca-4f9b-897c-6d2864ffaebb

comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
